server:
  port: 8085
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8888/eureka,http://eureka-server2:9999/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

EUREKA-PROVIDER:
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule
