server:
  port: 8085
spring:
  cloud:
    stream:
      binders:    #绑定消息中间件
        itheima_binder:
          type: rabbit
          envionment:
            spring:
              rabbitmq:
                virtual-host: /
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:  # 绑定通道
          binder: itheima_binder
          destinations: itheima_exchange


