spring:
  application:
    name: config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fudingcheng/springcloud-config
      label: master
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    virtual-host: /

server:
  port: 9876

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8888/eureka,http://eureka-server2:9999/eureka


# 暴露bus的刷新端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'