spring:
  application:
    name: hystrix.consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8888/eureka,http://eureka-server2:9999/eureka
server:
  port: 8088

feign:
  hystrix:
    enabled: true

