spring:
  application:
    name: eureka-server # 应用名称
server:
  port: 9999
eureka:
  instance:
    hostname: eureka-server2
    #prefer-ip-address: true  # 主机名
  client:
    service-url:
      defaultZone: http://eureka-server1:8888/eureka  # 注册中心地址
    register-with-eureka: false # 是否将自己注册到注册中心; eureka-server不需要
    fetch-registry: false      # 是否从注册中心抓取地址; eureka-server不需要